name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # ajuste se você usa outra branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ensure public/ exists and copy index.html if in repo root
        run: |
          mkdir -p public
          # Se você já colocou index.html dentro de public, o cp não sobrescreve
          if [ -f index.html ] && [ ! -f public/index.html ]; then
            cp index.html public/index.html
          fi
          # Para evitar upload acidental do firebase-config.js, adiciona ao .gitignore temporariamente (LOCAL)
          echo "public/firebase-config.js" >> .gitignore || true

      - name: Create firebase-config.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          mkdir -p public
          printf 'window.__firebase_config = %s;' "${FIREBASE_CONFIG}" > public/firebase-config.js
          echo "Created public/firebase-config.js (from secret)."

      - name: Show public files (debug)
        run: ls -la public || true

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1.8.0
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT }}

